# @name create-task
POST http://localhost:3333/tasks
Content-Type: application/json

{
	"title": "Buy some vegetables",
	"description": "That good to your health, believe me."
}

###

# @name get-task
GET http://localhost:3333/tasks

###

# @name update-task
PUT http://localhost:3333/tasks/3621adb7-bd47-45ca-a7d2-e95511860285
Content-Type: application/json

{
	"title": "Buy some vegetables (updated!)",
	"description": "That good to your health, believe me. (updated!)"
}

###

# @name delete-task
DELETE http://localhost:3333/tasks/f565c670-88ec-43fa-8c52-da17d2e8e86f

###

# @name complete-task
PATCH http://localhost:3333/tasks/a00b9832-2747-487a-8ec1-82bcb844e840/complete